### ISSUE TITLE
Spurious intellisense error 

### ISSUE THREAD

**Issue by diaphore** [danielscherzer/GLSL#16]
This small snippet raises intellisense errors :
```glsl
#version 460 core
layout(constant_id = 0) const uint foo = 123;
void main() {}
```
```
error C1319: can't apply layout to global variable 'foo'
error C7548: 'layout(constant_id) or layout(local_size_[xyz]_id)' requires "#extension GL_KHR_vulkan_glsl : enable" before use
```
On the other hand, it compiles fine with both the official `glslangValidator` and `glslc` :
```
$ glslc --target-env=opengl foo.comp
$ glslangValidator -G foo.comp
```

- Visual Studio 15.9.0 Preview 1.0
- GLSL 0.3.40

**Comment by danielscherzer** [comment]
Hi,
I can confirm this behavior. Compiling with both the official glslangValidator and glslc does not matter to the extension because it uses the current graphics cards driver to compile. For my system for instance this snipped raises:
```
fatal error C9999: *** exception during compilation ***
error C1319: can't apply layout to global variable 'foo'
error C7548: 'layout(constant_id) or layout(local_size_[xyz]_id)' requires "#extension GL_KHR_vulkan_glsl : enable" before use
```
with the NVIDIA 1060 as default and my INTEL 530 driver responds:
```
'constant_id' : syntax error syntax error
'' :  incorrect GLSL version: 460
'GL_ARB_explicit_attrib_location' :  extension is not available in current GLSL version
```
But the raised errors most probably will change depending on the driver version.
The intend of this extension is to check if the shader works on the current hardware. Checking if the shader code works on the glslLang and glslc compiler is currently not supported.

**Comment by diaphore** [comment]
Got it, thanks for the precision.
