### ISSUE TITLE
ISSUE: The extension doesn't work ERROR : [ 'OptionsPagePackage' package did not load correctly. ]

### ISSUE THREAD

**Issue by WildYss** [danielscherzer/GLSL#53]
### Installed product versions
- Visual Studio: [Community 2017 15.9.21]
- This extension: [0.7.95]

### Description
The extension simply doesn't work for me. Visual studio recognizes it and have enabled it, but it still doesn't work. One issue I found, is that when I go to **tools -> options -> GLSL language integration**, visual studio gives me an error:
```
The 'OptionsPagePackage' package did not load correctly.
The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\Me\AppData\Roaming\Microsoft\VisualStudio'\15.0_2b342d49\ActivityLog.xml'
```
### Extra info
1. There doesn't even seem to be a file named ActivityLog.xml in the specified path.
2. GLSL language integration is the only extension that I have, except for the default visual studio stuff.
### Steps to recreate
1. Download the extension from visual studio marketplace.
2. Install it with the downloaded vsix file.

**Comment by danielscherzer** [comment]
Could you try out an older version of the extension, like https://github.com/danielscherzer/GLSL/releases/tag/0.7.90
I did some cleanup of the extension, since I moved to Visual Studio 2019 and my first guess would be that I introduced some incompatibility to older versions of Visual Studio.

**Comment by stiffsen** [comment]
Hi. I had the same issue and even disabled all other extensions to check if it is a compatibility issue with any of them. It did not help. However, your version 0.7.90 works fine. Seems like your cleanup created a mess. ;-)

**Comment by danielscherzer** [comment]
@stiffsen and you also use Visual Studio: [Community 2017 15.9.21]?

**Comment by stiffsen** [comment]
@danielscherzer Ah sorry, I use Professional 2017 15.9.21.

**Comment by danielscherzer** [comment]
thanks for the feedback! so it seems that it is an incompatibility with 2017 versions of Visual Studio. The problem is that I did not find any documentation of Microsoft of how to make Extensions backward compatible with earlier versions of visual studio. My cleanup was long overdue updates to many nuget packages of Microsoft (some Vs 2019 users did complain about strange crashes). No dependencies to a Visual Studio version are mentioned with these packages anywhere, but my guess is that some of those packages are to blame.... I did a downgrade of some packages and pushed a new version to https://github.com/danielscherzer/GLSL/releases/tag/0.7.96 Please try out if this version works for you. This is blind testing for me because I have no version of VS 2017  installed to test.

**Comment by stiffsen** [comment]
That new version works for me. Thanks.

**Comment by WildYss** [comment]
The new version works for me as well. Thank you for the help!
