### ISSUE TITLE
Using @ in preprocessor constants

### ISSUE THREAD

**Issue by vtastek** [danielscherzer/GLSL#96]
### Installed product versions
- Visual Studio: 2019 Community

### Description
Using @ in preprocessor constants breaks syntax highlighting for the rest of the file.

### Steps to recreate
```
#if @useGPUShader4
    #extension GL_EXT_gpu_shader4: require
#endif

uniform mat4 projectionMatrix;
```
### Current behavior
```
#if @useGPUShader4
    #extension GL_EXT_gpu_shader4: require
#endif

uniform mat4 projectionMatrix;
```

### Expected behavior
(highlighted)
```glsl
#if @useGPUShader4
    #extension GL_EXT_gpu_shader4: require
#endif

uniform mat4 projectionMatrix;
```

**Comment by danielscherzer** [comment]
Thanks for your error report! 
Are you sure that a "@" is allowed inside an preprocessor constant?
The glsl spec and the c++ preprocessor specs only talk of an identifier, which is defined here https://docs.microsoft.com/en-us/cpp/cpp/identifiers-cpp?view=msvc-170

**Comment by vtastek** [comment]
I am not a C++ dev, so I can't really comment. But the parse code that added "@" was committed 5 years ago as a "shader manager", mentioning "shader templates".

**Comment by danielscherzer** [comment]
I published a new version that should allow you to use "@" in identifiers. Hope this helps!

**Comment by vtastek** [comment]
Thanks for the update, it works as expected now.

**Comment by AnyOldName3** [comment]
Just for context in case this makes someone break things, the `@` is an OpenMW-specific extension to GLSL as we run it through our own preprocessor before the GLSL preprocessor, and we wanted a way to make it clear when that was happening, so picked an otherwise-illegal character. Obviously, it's a bit better if having a rogue character only breaks the immediate area around it rather than the whole file, but it's probably sensible to still leave a red squiggle under the symbol containing the `@`.
